In [2]:
!pip install pymongo

Collecting pymongo
  Using cached pymongo-4.0.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (450 kB)
Installing collected packages: pymongo
Successfully installed pymongo-4.0.2
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the '/home/geev/Research/in_progress/Transgressions/transgressions-env/bin/python -m pip install --upgrade pip' command.

### DB to DF to pickle

In [2]:
from pymongo import MongoClient
import pandas as pd
from tqdm import tqdm
tqdm.pandas()

In [2]:
client = MongoClient()
db_metoo_tweets = client["jason_twitter"]
metoo_tweets = db_metoo_tweets.tweets

In [3]:
tweet_cursor = metoo_tweets.find({"condemnation_prediction":1})

In [17]:
columns = ["_id", "created_at", "retweet_count", "favorite_count",
           "severity_prediction", "condemnation_prediction", "is_quote_status", "reply_count", "retweeted",
           "target"] 
#           "RT_user_id", "user_id", "time_check", "body_target_mentions",
#            "quoted_status_target_mentions", "gnip_url_title_mentions"]

In [20]:
rows = []

In [28]:
for tweet in tqdm(tweet_cursor):
    row  = {col:tweet[col] for col in columns}
    row["user_id"] = tweet["user"]["id_str"]
    rows.append(row)

8181185it [28:07, 4846.73it/s]

In [29]:
jasDataFramendemnation_tweets = pd.DataFrame(rows)
jason_condemnation_tweets

,_id,created_at,retweet_count,favorite_count,severity_prediction,condemnation_prediction,is_quote_status,reply_count,retweeted,target,user_id
0,6383e2adfa2b796ff3841c46,Sun Sep 16 17:32:37 +0000 2018,0,0,2,1,True,1,False,steven_wilder_striegel,15685664
1,6383e2adfa2b796ff3841c4b,Sat Sep 15 02:57:08 +0000 2018,0,0,1,1,False,0,False,steven_wilder_striegel,182688169
2,6383e2adfa2b796ff3841c4c,Fri Sep 14 19:13:50 +0000 2018,0,0,1,1,False,1,False,steven_wilder_striegel,223816562
3,6383e2adfa2b796ff3841c4e,Fri Sep 14 15:10:54 +0000 2018,5,22,1,1,False,0,False,steven_wilder_striegel,1491965726
4,6383e2adfa2b796ff3841c4f,Fri Sep 14 14:16:25 +0000 2018,0,0,1,1,False,0,False,steven_wilder_striegel,16084002
...,...,...,...,...,...,...,...,...,...,...,...
8254416,6383fabbfa2b796ff3dd0153,Wed May 16 14:49:24 +0000 2018,0,0,1,1,False,0,False,george_tyndall,17686333
8254417,6383fabbfa2b796ff3dd015e,Wed May 16 03:26:01 +0000 2018,1,2,1,1,False,2,False,george_tyndall,855356208965746688
8254418,6383fabbfa2b796ff3dd0160,Wed May 16 02:53:37 +0000 2018,0,1,2,1,True,0,False,george_tyndall,632704303
8254419,6383fabbfa2b796ff3dd0167,Tue May 15 23:34:12 +0000 2018,0,0,2,1,False,0,False,george_tyndall,19888843
8254420,6383fabbfa2b796ff3dd016b,Tue May 15 21:20:03 +0000 2018,1,5,1,1,False,1,False,george_tyndall,350597282

In [33]:
jason_condemnation_tweets.to_csv("./data/jason_condemnation_tweets.csv")

In [3]:
jason_condemnation_tweets = pd.read_csv("./data/jason_condemnation_tweets.csv")

In [27]:
ambig_df = pd.read_csv("../data/20230302 ambiguity summary data.csv")
ambig_df

,target_name,overall_bad,familiar_person_,familiar_allegations_,veracity_allegations,severity_allegations,case_punishment
0,adam_venit,60.89444,1.231481,1.416667,63.63272,65.43210,55.43750
1,adrian_carrasquillo,54.44299,1.093458,1.084112,57.43614,57.43302,49.95561
2,al_franken,73.19804,2.568627,2.264706,76.13399,72.97059,71.16666
3,albert_j_alvarez,52.26364,1.129870,1.129870,49.56277,63.61039,45.77922
4,albert_schultz,75.97131,1.173913,1.139131,75.19710,78.90435,74.35217
...,...,...,...,...,...,...,...
257,wayne_pacelle,72.79895,1.147368,1.136842,75.27368,73.88772,70.12631
258,wesley_goodman,80.41333,1.122222,1.100000,78.53704,83.43333,79.55556
259,william_jacoby,60.81287,1.108911,1.099010,60.13861,66.37624,57.14604
260,william_kelley,60.88139,1.046512,1.046512,62.24419,63.88760,57.60465
261,william_strampel,83.74700,1.330000,1.370000,83.74000,84.42333,83.24500

In [28]:
set(jason_condemnation_tweets.target)

{'Earl_K_Sneed',
 'adam_venit',
 'adrian_carrasquillo',
 'al_franken',
 'albert_j_alvarez',
 'albert_schultz',
 'alec_klein',
 'alex_jones',
 'alex_kozinski',
 'allison_mack',
 'ameer_vann',
 'amit_singhal',
 'andre_passos',
 'andrea_ramsey',
 'andrew_creighton',
 'andrew_kreisberg',
 'andrÃ©_balazs',
 'andy_dick',
 'andy_henry',
 'andy_rubin',
 'andy_savage',
 'antonin_kratochvil',
 'asia_argento',
 'avital_ronell',
 'aziz_ansari',
 'barry_lubin',
 'ben_affleck',
 'ben_vereen',
 'benjamin_sparks',
 'benton_strong',
 'bill_hybels',
 'bill_oreilly',
 'blake_farenthold',
 'bob_weinstein',
 'bobby_scott',
 'borris_miles',
 'boyd_tinsley',
 'brad_kern',
 'brett_kavanaugh',
 'brett_ratner',
 'bruce_weber',
 'bryan_singer',
 'burns_strider',
 'calvin_smyre',
 'carlos_uresti',
 'charles_payne',
 'charles_schwertner',
 'charlie_hallowell',
 'charlie_rose',
 'charlie_walk',
 'chase_finlay',
 'chris_hardwick',
 'chris_sacca',
 'chris_savino',
 'christian_rodriguez',
 'clay_johnson',
 'cody_wilson',
 'corey_coleman',
 'corey_lewandowski',
 'cristiano_ronaldo',
 'cristina_garcia',
 'curtis_hill',
 'dan_harmon',
 'dan_johnson',
 'daniel_handler',
 'daniel_zwerdling',
 'danny_masterson',
 'dave_mcclure',
 'david_bellemere',
 'david_blaine',
 'david_copperfield',
 'david_corn',
 'david_keyes',
 'david_marchant',
 'dayan_candappa',
 'demos_parneros',
 'don_hazen',
 'donald_trump',
 'donovan_mcnabb',
 'dustin_hoffman',
 'dustin_marshall',
 'dwayne_duron_marshall',
 'dylan_howard',
 'ed_murray',
 'ed_westwick',
 'eddie_berganza',
 'eric_bauman',
 'eric_bolling',
 'eric_greitens',
 'eric_schneiderman',
 'eric_weinberger',
 'erick_guerrero',
 'ethan_kath',
 'francisco_ayala',
 'garrison_keillor',
 'gary_goddard',
 'geoffrey_rush',
 'george_hw_Bush',
 'george_takei',
 'george_tyndall',
 'glenn_thrush',
 'greg_kadel',
 'h_brandt_ayers',
 'hadrian_belove',
 'hamilton_fish',
 'harold_ford_jr',
 'harry_knowles',
 'harvey_weinstein',
 'heath_evans',
 'howie_rubin',
 'ike_taylor',
 'israel_horovitz',
 'james_franco',
 'james_levine',
 'james_rosen',
 'james_toback',
 'jann_wenner',
 'jason_mojica',
 'jean-claude_arnault',
 'jeff_franklin',
 'jeff_kruse',
 'jeffrey_klein',
 'jeffrey_tambor',
 'jeremy_piven',
 'jeremy_tooker',
 'jesse_lacey',
 'joel_kramer',
 'john_besh',
 'john_conyers',
 'john_hockenberry',
 'john_kenneally',
 'john_kricfalusi',
 'john_lasseter',
 'jon_heely',
 'jonathan_schwartz',
 'jorge_domÃ­nguez',
 'junot_dÃ­az',
 'justin_caldbeck',
 'kaj_larsen',
 'karl_templer',
 'keith_raniere',
 'ken_baker',
 'ken_friedman',
 'kevin_spacey',
 'kimberly_guilfoyle',
 'kirt_webster',
 'knight_landesman',
 'larry_nassar',
 'lars_von_trier',
 'lawrence_krauss',
 'leon_wieseltier',
 'leonard_lopate',
 'les_moonves',
 'lockhart_steele',
 'lorin_stein',
 'louis_ck',
 'luc_besson',
 'mario_batali',
 'mario_testino',
 'mark_halperin',
 'mark_mellor',
 'mark_schwahn',
 'marshall_faulk',
 'matt_dababneh',
 'matt_lauer',
 'matt_zimmerman',
 'matthew_weiner',
 'max_ogden',
 'mel_watt',
 'melanie_martinez',
 'michael_douglas',
 'michael_feinberg',
 'michael_ferro',
 'michael_hafford',
 'michael_oreskes',
 'michael_weatherly',
 'mike_germano',
 'mike_isabella',
 'mohamed_muqtar',
 'morgan_freeman',
 'morgan_spurlock',
 'murray_miller',
 'neil_degrasse_tyson',
 'nelly',
 'nicholas_kettle',
 'nicholas_nixon',
 'nick_caporella',
 'nick_carter',
 'nick_sauer',
 'oliver_stone',
 'patrick_demarchelier',
 'patrick_meehan',
 'patrick_witty',
 'paul_haggis',
 'paul_marciano',
 'paul_shapiro',
 'peter_aalbÃ¦k_jensen',
 'peter_martins',
 'philip_berk',
 'raul_bocanegra',
 'rhys_james',
 'richard_devaul',
 'richard_dreyfuss',
 'rick_day',
 'robert_knepper',
 'robert_moore',
 'robert_r_kelly',
 'robert_reece',
 'robert_scoble',
 'roland_g_fryer_jr',
 'roman_polanski',
 'ron_carlson',
 'ron_jeremy',
 'ross_levinsohn',
 'roy_moore',
 'roy_price',
 'rubÃ©n_kihuen',
 'russell_simmons',
 'ryan_lizza',
 'ryan_seacrest',
 'sam_isaly',
 'scott_baio',
 'scott_courtney',
 'sean_hannity',
 'sean_hutchison',
 'seth_sabal',
 'sherman_alexie',
 'shervin_pishevar',
 'stan_lee',
 'steve_butts',
 'steve_lebsock',
 'steve_wynn',
 'steven_seagal',
 'steven_wilder_striegel',
 'sylvester_stallone',
 't_florian_jaeger',
 'tavis_smiley',
 'terdema_ussery',
 'tj_miller',
 'todd_heatherton',
 'tom_ashbrook',
 'tom_brokaw',
 'tom_frieden',
 'tom_sizemore',
 'tony_cÃ¡rdenas',
 'tony_mendoza',
 'travis_kalanick',
 'trent_franks',
 'tyler_grasham',
 'vince_ingenito',
 'vincent_cirrincione',
 'wayne_pacelle',
 'wesley_goodman',
 'william_jacoby',
 'william_kelley',
 'william_strampel'}

In [34]:
jason_condemnation_tweets[jason_condemnation_tweets.target == "max_ogden"]

,Unnamed: 0,_id,created_at,retweet_count,favorite_count,severity_prediction,condemnation_prediction,is_quote_status,reply_count,retweeted,target,user_id
2124715,2124715,6383e985fa2b796ff3e685e0,Thu Dec 21 22:47:06 +0000 2017,11,52,1,1,False,2,False,max_ogden,13461

In [31]:
set(jason_condemnation_tweets.target)-set(ambig_df.target_name)

{'max_ogden'}

In [32]:
set(ambig_df.target_name)-set(jason_condemnation_tweets.target)

{'caleb_jennings',
 'ed_crane',
 'frankie_shaw',
 'gerard_depardieu',
 'kevin_braun',
 'paul_whalen',
 'shadie_elnashai'}

In [30]:
for target_name in tqdm(ambig_df.target_name): 
    l = len(jason_condemnation_tweets[jason_condemnation_tweets.target==target_name])
    if not l:
        print(target_name)

  3%|â–Ž         | 9/262 [00:03<01:27,  2.89it/s]

KeyboardInterrupt:

In [18]:
for col in columns:
    print(col, tweet[col])

_id 6383e2adfa2b796ff3841c3f
created_at Tue Sep 18 14:47:50 +0000 2018
retweet_count 1
favorite_count 2
severity_prediction 1
condemnation_prediction 1
is_quote_status False
reply_count 0
retweeted False
target steven_wilder_striegel

In [5]:
cursor = metoo_tweets.find({"is_RT":True, "condemnation_prediction":1})
print("1")
list_cur = list(cursor)
print("2")
df = pd.DataFrame(list_cur)
print("3")
df

1
2
3

,_id,body,postedTime,retweetCount,favoritesCount,quoted_status_id,quoted_status_user_id,quoted_status_body,quoted_status_user_postedTime,gnip_url_title,...,condemnation_logit_1,condemnation_prediction,gnip_url_title_mentions_validated,gnip_url_title_mentions_validated_true,quoted_status_target_mentions_validated,quoted_status_target_mentions_validated_true,severity_logit_0,severity_logit_1,severity_logit_2,severity_prediction
0,6234d5381c978b7d87a2736d,RT @RealSaavedra: Want to know why the media i...,2017-10-31 04:00:00,3476,4042,None,None,None,NaT,[],...,1.429047,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6234d5381c978b7d87a2736f,"RT @ItsJaimeHere: Damn, didn't realize that Am...",2017-10-31 04:00:01,146,379,None,None,None,NaT,[],...,1.534165,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6234d5381c978b7d87a27373,RT @samkalidi: Kevin Spacey's predatory behavi...,2017-10-31 04:00:10,1010,1565,None,None,None,NaT,[],...,1.239513,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6234d5381c978b7d87a27375,RT @rilaws: The psychology of the closet is da...,2017-10-31 04:00:14,2748,10274,924850370341322753,21630311,Holy shit. https://t.co/B7d1uGjOQM,2017-10-30 04:08:05,[],...,2.026769,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6234d5381c978b7d87a27376,RT @MattWalshBlog: A lot of people saying they...,2017-10-31 04:00:18,460,1753,None,None,None,NaT,[],...,1.443937,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5665499,623538a01c978b7d8784407c,RT @EsotericCD: Harvey Weinstein's victims may...,2017-10-06 21:18:57,190,224,None,None,None,NaT,[Why the Weinstein Sexual Harassment Allegatio...,...,1.585171,1,[weinstein],True,NaN,NaN,-1.493573,1.450577,-0.057241,1.0
5665500,623538a01c978b7d8784407f,"RT @kerpen: Everyone who knew is complicit, wh...",2017-10-06 21:19:40,725,1668,916030035890462720,14529929,"Hollywood producer I know: ""Shocked itâ€™s taken...",2017-10-05 19:59:14,[],...,1.850414,1,NaN,NaN,[weinstein],True,-0.061966,1.420318,-1.183103,1.0
5665501,623538a01c978b7d87844081,"RT @kerpen: Everyone who knew is complicit, wh...",2017-10-06 21:19:49,726,1669,916030035890462720,14529929,"Hollywood producer I know: ""Shocked itâ€™s taken...",2017-10-05 19:59:14,[],...,1.850414,1,NaN,NaN,[weinstein],True,-0.061966,1.420318,-1.183103,1.0
5665502,623538a01c978b7d87844082,RT @TesserBarbara: @JulianAssange Apparently M...,2017-10-06 21:19:54,1,0,None,None,None,NaT,[],...,0.665652,1,NaN,NaN,NaN,NaN,0.884040,0.865989,-1.489366,0.0
5665503,623538a01c978b7d87844083,RT @DonaldJTrumpJr: Will She/they all Disavow?...,2017-10-06 21:19:56,4001,8772,None,None,None,NaT,[Will She Disavow? Embattled Hollywood Produce...,...,1.155557,1,[weinstein],True,NaN,NaN,-0.763057,1.385295,-0.793496,1.0

In [7]:
df.columns

Index(['_id', 'body', 'postedTime', 'retweetCount', 'favoritesCount',
       'quoted_status_id', 'quoted_status_user_id', 'quoted_status_body',
       'quoted_status_user_postedTime', 'gnip_url_title',
       'gnip_url_description', 'is_RT', 'RT_body', 'RT_user_id', 'RT_id',
       'tweet_id', 'user_id', 'RT_target_mentions', 'body_target_mentions',
       'body_target_mentions_validated', 'body_target_mentions_validated_true',
       'gnip_url_title_mentions', 'lang_pred', 'lang_pred_prob',
       'quoted_status_target_mentions', 'clean_targets_n', 'clean_tweet',
       'clean_tweet_masked', 'mask_map', 'modified_quote_tweet', 'time_check',
       'condemnation_logit_1', 'condemnation_prediction',
       'gnip_url_title_mentions_validated',
       'gnip_url_title_mentions_validated_true',
       'quoted_status_target_mentions_validated',
       'quoted_status_target_mentions_validated_true', 'severity_logit_0',
       'severity_logit_1', 'severity_logit_2', 'severity_prediction'],
      dtype='object')

In [8]:
import pickle
# open a file, where you ant to store the data
file = open('./data/condemnation_RTs.p', 'wb')

# dump information to that file
pickle.dump(df, file)

# close the file
file.close()

### Filtering Data for Anlaysis

In [6]:
from tqdm import tqdm

In [8]:
tqdm.pandas()

In [1]:
import pickle

with open("./data/condemnation_RTs.p", "rb") as f:
    df = pickle.load(f)
df

,_id,body,postedTime,retweetCount,favoritesCount,quoted_status_id,quoted_status_user_id,quoted_status_body,quoted_status_user_postedTime,gnip_url_title,...,condemnation_logit_1,condemnation_prediction,gnip_url_title_mentions_validated,gnip_url_title_mentions_validated_true,quoted_status_target_mentions_validated,quoted_status_target_mentions_validated_true,severity_logit_0,severity_logit_1,severity_logit_2,severity_prediction
0,6234d5381c978b7d87a2736d,RT @RealSaavedra: Want to know why the media i...,2017-10-31 04:00:00,3476,4042,None,None,None,NaT,[],...,1.429047,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6234d5381c978b7d87a2736f,"RT @ItsJaimeHere: Damn, didn't realize that Am...",2017-10-31 04:00:01,146,379,None,None,None,NaT,[],...,1.534165,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6234d5381c978b7d87a27373,RT @samkalidi: Kevin Spacey's predatory behavi...,2017-10-31 04:00:10,1010,1565,None,None,None,NaT,[],...,1.239513,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6234d5381c978b7d87a27375,RT @rilaws: The psychology of the closet is da...,2017-10-31 04:00:14,2748,10274,924850370341322753,21630311,Holy shit. https://t.co/B7d1uGjOQM,2017-10-30 04:08:05,[],...,2.026769,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6234d5381c978b7d87a27376,RT @MattWalshBlog: A lot of people saying they...,2017-10-31 04:00:18,460,1753,None,None,None,NaT,[],...,1.443937,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5665499,623538a01c978b7d8784407c,RT @EsotericCD: Harvey Weinstein's victims may...,2017-10-06 21:18:57,190,224,None,None,None,NaT,[Why the Weinstein Sexual Harassment Allegatio...,...,1.585171,1,[weinstein],True,NaN,NaN,-1.493573,1.450577,-0.057241,1.0
5665500,623538a01c978b7d8784407f,"RT @kerpen: Everyone who knew is complicit, wh...",2017-10-06 21:19:40,725,1668,916030035890462720,14529929,"Hollywood producer I know: ""Shocked itâ€™s taken...",2017-10-05 19:59:14,[],...,1.850414,1,NaN,NaN,[weinstein],True,-0.061966,1.420318,-1.183103,1.0
5665501,623538a01c978b7d87844081,"RT @kerpen: Everyone who knew is complicit, wh...",2017-10-06 21:19:49,726,1669,916030035890462720,14529929,"Hollywood producer I know: ""Shocked itâ€™s taken...",2017-10-05 19:59:14,[],...,1.850414,1,NaN,NaN,[weinstein],True,-0.061966,1.420318,-1.183103,1.0
5665502,623538a01c978b7d87844082,RT @TesserBarbara: @JulianAssange Apparently M...,2017-10-06 21:19:54,1,0,None,None,None,NaT,[],...,0.665652,1,NaN,NaN,NaN,NaN,0.884040,0.865989,-1.489366,0.0
5665503,623538a01c978b7d87844083,RT @DonaldJTrumpJr: Will She/they all Disavow?...,2017-10-06 21:19:56,4001,8772,None,None,None,NaT,[Will She Disavow? Embattled Hollywood Produce...,...,1.155557,1,[weinstein],True,NaN,NaN,-0.763057,1.385295,-0.793496,1.0

In [2]:
df["severity_prediction"].value_counts()

1.0    3706666
0.0    1235982
2.0     622856
Name: severity_prediction, dtype: int64

Dropping unnecessary columns

In [3]:
columns = ["_id", "postedTime", "retweetCount", "favoritesCount",
           "severity_prediction", "condemnation_prediction", 
          "RT_user_id", "user_id", "time_check", "body_target_mentions",
           "quoted_status_target_mentions", "gnip_url_title_mentions"] 
subset = df[columns]

Dropping rows that don't have a single valid time_check

In [4]:
def has_valid_time(row):
#     print(row)
    for key in row["time_check"]:
        if row["time_check"][key]["valid"]:
            return True
    return False

In [9]:
subset["time_valid"] = subset.progress_apply(lambda row: has_valid_time(row), axis=1)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 5665504/5665504 [01:33<00:00, 60821.50it/s]
/home/geev/Research/in_progress/Transgressions/transgressions-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
subset = subset[subset["time_valid"]]

In [11]:
subset

,_id,postedTime,retweetCount,favoritesCount,severity_prediction,condemnation_prediction,RT_user_id,user_id,time_check,body_target_mentions,quoted_status_target_mentions,gnip_url_title_mentions,time_valid
0,6234d5381c978b7d87a2736d,2017-10-31 04:00:00,3476,4042,NaN,1,812135885328236551,824629442781806593,"{'spacey': {'valid': True, 'public_date': 2017...",[spacey],None,None,True
1,6234d5381c978b7d87a2736f,2017-10-31 04:00:01,146,379,NaN,1,1219781474,604881881,"{'spacey': {'valid': True, 'public_date': 2017...",[spacey],None,None,True
2,6234d5381c978b7d87a27373,2017-10-31 04:00:10,1010,1565,NaN,1,102475469,748234219,"{'spacey': {'valid': True, 'public_date': 2017...",[spacey],None,None,True
3,6234d5381c978b7d87a27375,2017-10-31 04:00:14,2748,10274,NaN,1,106111147,1730677554,"{'spacey': {'valid': True, 'public_date': 2017...",[spacey],[],None,True
4,6234d5381c978b7d87a27376,2017-10-31 04:00:18,460,1753,NaN,1,1500129642,247906909,"{'spacey': {'valid': True, 'public_date': 2017...",[spacey],None,None,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5665499,623538a01c978b7d8784407c,2017-10-06 21:18:57,190,224,1.0,1,161163311,830109389230977024,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein, weinstein]",None,[weinstein],True
5665500,623538a01c978b7d8784407f,2017-10-06 21:19:40,725,1668,1.0,1,6724252,22328632,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein]",[weinstein],None,True
5665501,623538a01c978b7d87844081,2017-10-06 21:19:49,726,1669,1.0,1,6724252,486995811,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein]",[weinstein],None,True
5665502,623538a01c978b7d87844082,2017-10-06 21:19:54,1,0,0.0,1,816291122804686848,784907880394743808,"{'weinstein': {'valid': True, 'public_date': 2...",[weinstein],None,None,True
5665503,623538a01c978b7d87844083,2017-10-06 21:19:56,4001,8772,1.0,1,39344374,3362315553,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein, weinstein]",None,[weinstein],True

Gathering all targets

In [78]:
def set_targets(row):
    res = []
    for col in ["body_target_mentions", "quoted_status_target_mentions", "gnip_url_title_mentions"]:
#         print(col)
        if not row[col]:
            continue
        for target in row[col]:
            
            if target not in res:
                res.append(target)
    return res

In [79]:
subset["targets"] = subset.progress_apply(lambda row: set_targets(row), axis=1)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3126598/3126598 [01:28<00:00, 35137.82it/s]

In [82]:
subset = subset.dropna(subset=["severity_prediction", "favoritesCount", "retweetCount"])

In [83]:
subset

,_id,postedTime,retweetCount,favoritesCount,severity_prediction,condemnation_prediction,RT_user_id,user_id,time_check,body_target_mentions,quoted_status_target_mentions,gnip_url_title_mentions,time_valid,targets
100000,6234d6c81c978b7d87a676fa,2017-11-10 02:45:17,390,557,1.0,1,2496335227,776493304791855104,"{'louis_ck': {'valid': True, 'public_date': 20...","[louis_ck, halperin, weinstein, spacey, moore]",None,[],True,"[louis_ck, halperin, weinstein, spacey, moore]"
100001,6234d6c81c978b7d87a676ff,2017-11-10 02:49:54,2089,10752,1.0,1,289342771,14896102,"{'louis_ck': {'valid': True, 'public_date': 20...",[louis_ck],None,None,True,[louis_ck]
100002,6234d6c81c978b7d87a67703,2017-11-10 02:49:58,533,1131,1.0,1,81482674,158451341,"{'louis_ck': {'valid': True, 'public_date': 20...",[louis_ck],None,None,True,[louis_ck]
100003,6234d6c81c978b7d87a67704,2017-11-10 02:49:58,77,201,1.0,1,4280734823,771355205443149824,"{'louis_ck': {'valid': True, 'public_date': 20...","[louis_ck, weinstein, spacey, toback, louis_ck...","[louis_ck, weinstein, spacey, toback]",None,True,"[louis_ck, weinstein, spacey, toback]"
100004,6234d6c81c978b7d87a67708,2017-11-10 02:49:04,2084,10738,1.0,1,289342771,819667363545174023,"{'louis_ck': {'valid': True, 'public_date': 20...",[louis_ck],None,None,True,[louis_ck]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5665499,623538a01c978b7d8784407c,2017-10-06 21:18:57,190,224,1.0,1,161163311,830109389230977024,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein, weinstein]",None,[weinstein],True,[weinstein]
5665500,623538a01c978b7d8784407f,2017-10-06 21:19:40,725,1668,1.0,1,6724252,22328632,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein]",[weinstein],None,True,[weinstein]
5665501,623538a01c978b7d87844081,2017-10-06 21:19:49,726,1669,1.0,1,6724252,486995811,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein]",[weinstein],None,True,[weinstein]
5665502,623538a01c978b7d87844082,2017-10-06 21:19:54,1,0,0.0,1,816291122804686848,784907880394743808,"{'weinstein': {'valid': True, 'public_date': 2...",[weinstein],None,None,True,[weinstein]
5665503,623538a01c978b7d87844083,2017-10-06 21:19:56,4001,8772,1.0,1,39344374,3362315553,"{'weinstein': {'valid': True, 'public_date': 2...","[weinstein, weinstein, weinstein]",None,[weinstein],True,[weinstein]

In [84]:
subset.to_csv("./data/filtered_condemnation_RTs.csv", index=False)

In [67]:
df= pd.read_csv("./data/filtered_condemnation_RTs.csv")

,_id,postedTime,retweetCount,favoritesCount,severity_prediction,condemnation_prediction,RT_user_id,user_id,time_check,body_target_mentions,quoted_status_target_mentions,gnip_url_title_mentions,time_valid,targets
54323,6234d6c81c978b7d87a676fa,2017-11-10 02:45:17,390,557,1.0,1,2.496335e+09,776493304791855104,"{'louis_ck': {'valid': True, 'public_date': da...","['louis_ck', 'halperin', 'weinstein', 'spacey'...",NaN,[],True,"['louis_ck', 'halperin', 'weinstein', 'spacey'..."
54324,6234d6c81c978b7d87a676ff,2017-11-10 02:49:54,2089,10752,1.0,1,2.893428e+08,14896102,"{'louis_ck': {'valid': True, 'public_date': da...",['louis_ck'],NaN,NaN,True,['louis_ck']
54325,6234d6c81c978b7d87a67703,2017-11-10 02:49:58,533,1131,1.0,1,8.148267e+07,158451341,"{'louis_ck': {'valid': True, 'public_date': da...",['louis_ck'],NaN,NaN,True,['louis_ck']
54326,6234d6c81c978b7d87a67704,2017-11-10 02:49:58,77,201,1.0,1,4.280735e+09,771355205443149824,"{'louis_ck': {'valid': True, 'public_date': da...","['louis_ck', 'weinstein', 'spacey', 'toback', ...","['louis_ck', 'weinstein', 'spacey', 'toback']",NaN,True,"['louis_ck', 'weinstein', 'spacey', 'toback']"
54327,6234d6c81c978b7d87a67708,2017-11-10 02:49:04,2084,10738,1.0,1,2.893428e+08,819667363545174023,"{'louis_ck': {'valid': True, 'public_date': da...",['louis_ck'],NaN,NaN,True,['louis_ck']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3126593,623538a01c978b7d8784407c,2017-10-06 21:18:57,190,224,1.0,1,1.611633e+08,830109389230977024,"{'weinstein': {'valid': True, 'public_date': d...","['weinstein', 'weinstein', 'weinstein']",NaN,['weinstein'],True,['weinstein']
3126594,623538a01c978b7d8784407f,2017-10-06 21:19:40,725,1668,1.0,1,6.724252e+06,22328632,"{'weinstein': {'valid': True, 'public_date': d...","['weinstein', 'weinstein']",['weinstein'],NaN,True,['weinstein']
3126595,623538a01c978b7d87844081,2017-10-06 21:19:49,726,1669,1.0,1,6.724252e+06,486995811,"{'weinstein': {'valid': True, 'public_date': d...","['weinstein', 'weinstein']",['weinstein'],NaN,True,['weinstein']
3126596,623538a01c978b7d87844082,2017-10-06 21:19:54,1,0,0.0,1,8.162911e+17,784907880394743808,"{'weinstein': {'valid': True, 'public_date': d...",['weinstein'],NaN,NaN,True,['weinstein']
3126597,623538a01c978b7d87844083,2017-10-06 21:19:56,4001,8772,1.0,1,3.934437e+07,3362315553,"{'weinstein': {'valid': True, 'public_date': d...","['weinstein', 'weinstein', 'weinstein']",NaN,['weinstein'],True,['weinstein']

In [68]:
df["severity_prediction"].value_counts()

1.0    2055905
0.0     632186
2.0     384184
Name: severity_prediction, dtype: int64

In [33]:
import pickle
# open a file, where you ant to store the data
file = open('./data/RT_tweets.p', 'wb')

# dump information to that file
pickle.dump(df, file)

# close the file
file.close()